# Generated by Django 3.0 on 2019-12-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=100)),
                ('slider_dsc', models.CharField(max_length=100)),
                ('slider_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
