# Generated by Django 3.0 on 2019-12-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=100)),
                ('product_desc', models.CharField(max_length=1000)),
                ('cat_name', models.CharField(max_length=100)),
                ('bran_name', models.CharField(max_length=100)),
                ('price', models.ImageField(upload_to='')),
                ('quantity', models.ImageField(upload_to='')),
                ('status', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
